include: package:very_good_analysis/analysis_options.yaml

analyzer:
  exclude:
    - "**/*.mocks.dart"
    - "**/*.g.dart"
  plugins:
    - dart_code_metrics

linter:
  rules:
    # Disabled because it seems a bit overkill for non open-source projects.
    # You should still provide adequate documentation on features.
    public_member_api_docs: false

dart_code_metrics:
  anti-patterns:
    - long-method
    - long-parameter-list
  metrics:
    cyclomatic-complexity: 20
    maximum-nesting-level: 5
    number-of-parameters: 4
    source-lines-of-code: 50
  metrics-exclude:
    - test/**
  rules:
    - no-boolean-literal-compare
    - prefer-trailing-comma
    - prefer-conditional-expressions
    - no-equal-then-else
  rules-exclude:
    - test/**
