include: package:very_good_analysis/analysis_options.yaml

analyzer:
  exclude:
    - "**/*.mocks.dart"
    - "**/*.g.dart"
    - "**/*.gr.dart"
    - "**/*.freezed.dart"
  plugins:
    - dart_code_metrics

linter:
  rules:
    public_member_api_docs: false
    use_super_parameters: true
#    flutter_style_todos: false
#    always_put_required_named_parameters_first: true
#    sort_constructors_first: true
#    prefer_single_quotes: true
#    sort_pub_dependencies: true
#    always_use_package_imports: false
#    prefer_relative_imports: true
#    depend_on_referenced_packages: false
#    avoid_classes_with_only_static_members: false


dart_code_metrics:
  anti-patterns:
    - long-method
    - long-parameter-list
  metrics:
    cyclomatic-complexity: 20
    maximum-nesting-level: 5
    number-of-parameters: 4
    source-lines-of-code: 50
  metrics-exclude:
    - test/**
  rules:
    - no-boolean-literal-compare
    - prefer-trailing-comma
    - prefer-conditional-expressions
    - no-equal-then-else
    # - no-empty-block
  rules-exclude:
    - test/**
