name: funda_assignment
description: Assignment for Funda.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  dio: ^4.0.6
  fpdart: ^0.2.0
  intl: ^0.17.0
  json_annotation: ^4.6.0
  provider: ^6.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.2.0
  json_serializable: ^6.3.1
  very_good_analysis: ^3.0.1

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
